export const worksheetTerms = [
  { number: 1, section: 1, term: 'ハードウェア', meaning: 'コンピュータを構成する本体の装置や周辺機器。' },
  { number: 2, section: 1, term: 'CPU', meaning: '中央処理装置。制御装置と演算装置を合わせたもの。' },
  { number: 3, section: 1, term: 'インタフェース', meaning: '機器・ソフトウェア・人の間で、情報をやり取りするための規格や機能。' },
  { number: 4, section: 1, term: 'Type-A', meaning: 'USB端子の形状の一つ。長方形で、差し込む向きが決まっている。' },
  { number: 5, section: 1, term: 'Type-C', meaning: 'USB端子の形状の一つ。上下を区別せず差し込める。形状だけで速度や映像対応はわからない。' },
  { number: 6, section: 1, term: 'HDMI', meaning: '映像と音声をディスプレイなどへ送るデジタル接続規格。' },
  { number: 7, section: 1, term: 'DisplayPort', meaning: '映像と音声をディスプレイなどへ送るデジタル接続規格。' },
  { number: 8, section: 1, term: 'Bluetooth', meaning: 'イヤホンやマウスなどの接続に使われる無線通信技術。通信距離は機器と環境で変わる。' },
  { number: 9, section: 1, term: 'NFC', meaning: '機器を近づけて使う近距離無線通信。非接触の決済などで利用される。' },
  { number: 10, section: 1, term: 'IEEE 802.11', meaning: '無線LANの標準規格の系列。周波数帯や速度などの違いがある。' },
  { number: 11, section: 2, term: 'デバイスドライバ', meaning: 'OSと機器の橋渡しをし、機器を制御するプログラム。' },
  { number: 12, section: 2, term: 'API', meaning: 'ソフトウェアの機能を別のソフトウェアから利用するための窓口や取り決め。' },
  { number: 13, section: 2, term: 'タスク管理', meaning: 'ソフトウェアの実行順序や、CPUを使う時間の割り当てなどを管理する。' },
  { number: 14, section: 2, term: '入出力管理', meaning: '周辺機器とのデータの入出力を管理する。' },
  { number: 15, section: 2, term: 'ファイル管理', meaning: 'ファイルの保存・読み出しや、フォルダによる整理などを管理する。' },
  { number: 16, section: 2, term: '資源管理', meaning: 'CPU・メモリ・周辺機器などのコンピュータ資源を管理する。' },
  { number: 17, section: 2, term: 'ユーザ管理', meaning: '利用者のアカウントの登録・削除などを管理する。' },
  { number: 18, section: 3, term: '.jpg', meaning: 'JPEG形式の画像ファイルに使う拡張子。.jpegも使われる。' },
  { number: 19, section: 3, term: '.zip', meaning: '複数のファイルなどをまとめられるZIP形式の拡張子。' },
  { number: 20, section: 3, term: '.txt', meaning: '文字を中心に記録したテキストファイルの拡張子。' },
  { number: 21, section: 3, term: '.pdf', meaning: '文書のレイアウトを保って共有するPDF形式の拡張子。' },
] as const;

export const hardwareSteps = [
  { actors: ['input'], speaker: '入力装置さん', line: '「3＋5」が入力されたよ！ CPUのみんな、受け取って！', packet: '3＋5', route: '入力装置 → CPU', memory: 'まだ空', slots: ['', '', '', ''] },
  { actors: ['control'], speaker: '制御装置くん', line: '計算に使うデータだね。主記憶ちゃん、「3は箱1、5は箱2へ入れて」と指示を送るよ！', packet: '箱1＝3／箱2＝5', route: '制御装置 ⇢ 主記憶装置へ書き込み指示', memory: 'まだ書き込み前', slots: ['', '', '', ''] },
  { actors: ['memory'], speaker: '主記憶ちゃん', line: '指示とデータを受け取ったよ。3を箱1、5を箱2へ入れたよ！', packet: '3　5', route: '主記憶装置：箱1・箱2へ書き込み', memory: '箱1＝3／箱2＝5', slots: ['3', '5', '', ''] },
  { actors: ['control', 'arithmetic'], speaker: '制御装置くん', line: 'これは足し算だ。演算装置くん、主記憶ちゃんの箱1と箱2の中身を足して、答えを箱4へ返して！', packet: '箱1＋箱2 → 箱4', route: '制御装置 ⇢ 演算装置へ指示', memory: '箱1＝3／箱2＝5', slots: ['3', '5', '', ''] },
  { actors: ['memory', 'arithmetic'], speaker: '主記憶ちゃん', line: '箱1から「3」、箱2から「5」を読み出したよ。演算装置くんへ渡すね！', packet: '3　5', route: '主記憶装置 → 演算装置へ読み出し', memory: '箱1＝3／箱2＝5', slots: ['3', '5', '', ''] },
  { actors: ['arithmetic'], speaker: '演算装置くん', line: '3＋5＝8だね。主記憶ちゃん、「8を箱4へ入れて」と書き込みを頼むよ！', packet: '箱4＝8', route: '演算装置 → 主記憶装置へ結果と指示', memory: '箱4はまだ空', slots: ['3', '5', '', ''] },
  { actors: ['memory'], speaker: '主記憶ちゃん', line: '計算結果の「8」を受け取って、箱4に入れたよ！', packet: '8', route: '主記憶装置：箱4へ書き込み', memory: '箱1＝3／箱2＝5／箱4＝8', slots: ['3', '5', '', '8'] },
  { actors: ['control', 'output'], speaker: '制御装置くん', line: '計算が終わった！ 出力装置くん、主記憶ちゃんの箱4を画面へ表示して！', packet: '箱4を表示', route: '制御装置 ⇢ 出力装置へ指示', memory: '箱4＝8', slots: ['3', '5', '', '8'] },
  { actors: ['memory', 'output'], speaker: '出力装置くん', line: '主記憶ちゃんの箱4から「8」を受け取ったよ。ぼくが画面へ「8」を渡して表示するね！', packet: '8', route: '主記憶装置の箱4 → 出力装置 → 画面', memory: '箱4＝8', slots: ['3', '5', '', '8'] },
  { actors: ['control', 'storage'], speaker: '制御装置くん', line: 'この結果を残しておこう。補助記憶お母さん、主記憶ちゃんの箱4を保存して！', packet: '箱4を保存せよ', route: '制御装置 ⇢ 補助記憶装置へ指示', memory: '箱4＝8', slots: ['3', '5', '', '8'] },
  { actors: ['memory', 'storage'], speaker: '主記憶ちゃん', line: '制御装置くんの指示だね。箱4の「8」を補助記憶お母さんへ渡すよ！', packet: '8', route: '主記憶装置の箱4 → 補助記憶装置', memory: '箱4の8を受け渡し中', slots: ['3', '5', '', '8'] },
  { actors: ['storage'], speaker: '補助記憶お母さん', line: '箱4の「8」を受け取ったよ。SSDへ保存したから、電源を切っても残るよ。', packet: '保存完了', route: 'SSDなどへ保存完了', memory: '主記憶：3・5・8を使用中／補助記憶：8', slots: ['3', '5', '', '8'] },
  { actors: ['control'], speaker: '制御装置くん', line: '計算・表示・保存が終わったよ。この物語ではぼくが代表して、箱1・箱2・箱4の作業領域を解放するよう伝えるね！', packet: '箱1・2・4を解放', route: '制御装置 ⇢ 主記憶装置へ解放指示', memory: '解放指示を受信', slots: ['3', '5', '', '8'] },
  { actors: ['memory'], speaker: '主記憶ちゃん', line: '作業領域を解放したよ。次の処理で再利用できるね！', packet: '作業領域を解放', route: '主記憶装置の領域を再利用可能に', memory: '実機ではOSなどが管理し、値を消去せず領域を再利用することもある', slots: ['', '', '', ''] },
] as const;

export const connections = [
  { id: 'type-a', name: 'USB Type-A', number: 4, group: '有線', detail: 'キーボード、マウス、USBメモリなど。端子の形状の名前であり、通信速度の名前ではない。', shape: '長方形・向きあり' },
  { id: 'type-c', name: 'USB Type-C', number: 5, group: '有線', detail: 'USBメモリなどの接続や充電。対応機器では映像も送れるが、端子・ケーブルの機能確認が必要。', shape: '小さな長円形・上下対称' },
  { id: 'hdmi', name: 'HDMI', number: 6, group: '有線', detail: 'ディスプレイやプロジェクタへ、デジタルの映像と音声を送る。', shape: 'Type A・下の2角を落とした形' },
  { id: 'displayport', name: 'DisplayPort', number: 7, group: '有線', detail: 'ディスプレイなどへ、デジタルの映像と音声を送る。', shape: '片側の角を落とした形' },
  { id: 'vga', name: 'VGA', number: null, group: '有線', detail: 'ディスプレイやプロジェクタへアナログの映像を送る。音声は別の接続が必要。', shape: '3段のピン・固定ねじ' },
  { id: 'bluetooth', name: 'Bluetooth', number: 8, group: '無線', detail: 'イヤホンやマウスなどに使う。プリントの距離は目安であり、機器や障害物などで通信できる範囲は変わる。', shape: '周辺機器を無線でつなぐ' },
  { id: 'nfc', name: 'NFC', number: 9, group: '無線', detail: '機器を近づけて通信する。非接触の決済などで利用される。', shape: '近づけてタッチ' },
  { id: 'wifi', name: 'IEEE 802.11', number: 10, group: '無線', detail: '無線LANの標準規格の系列。対応するアクセスポイントを通して、端末をネットワークへ接続できる。', shape: '無線LANの規格' },
] as const;

export const connectionQuestions = [
  { left: 'パソコン', right: 'キーボード', text: 'キーボードを、パソコンへ有線でつなぎたい。', focus: ['キーボード', '有線', '端子の形を見よう'], choices: ['type-a', 'hdmi', 'nfc'], answer: 'type-a', reason: 'このキーボードとパソコンにはUSB Type-A端子があるため、USBで接続できます。' },
  { left: '薄型パソコン', right: 'USBメモリ（Type-C）', text: 'このUSBメモリを、変換器なしで直接つなぎたい。', focus: ['小さな長円形', '上下対称'], choices: ['type-c', 'displayport', 'bluetooth'], answer: 'type-c', reason: 'USBメモリのType-C端子とパソコンの端子の形が合うため、直接接続できます。形が同じでも機能や速度は製品ごとに確認します。' },
  { left: 'パソコン', right: 'プロジェクタ', text: '映像と音声を、1本のデジタルケーブルで送りたい。', focus: ['映像＋音声', '1本', 'デジタル'], choices: ['vga', 'hdmi', 'type-a'], answer: 'hdmi', reason: 'HDMIはデジタルの映像と音声を一緒に送れます。VGAは映像だけです。' },
  { left: 'パソコン', right: 'ディスプレイ', text: '映像と音声を、1本のデジタルケーブルで送りたい。', focus: ['映像＋音声', '1本', 'デジタル'], choices: ['displayport', 'nfc', 'type-a'], answer: 'displayport', reason: 'この選択肢ではDisplayPortが、デジタルの映像と音声を1本で送れます。' },
  { left: '古いパソコン', right: '古いプロジェクタ', text: '青い15本ピンの端子で、映像だけを送りたい。', focus: ['映像だけ', 'アナログ', '15ピン'], choices: ['vga', 'hdmi', 'wifi'], answer: 'vga', reason: 'VGAはアナログ映像を送ります。音声は別の接続が必要です。' },
  { left: 'スマートフォン', right: 'ワイヤレスイヤホン', text: '近くのイヤホンへ、ケーブルなしで音声を送りたい。', focus: ['近く', '音声', '無線'], choices: ['bluetooth', 'nfc', 'wifi'], answer: 'bluetooth', reason: 'Bluetoothは近くのイヤホンやマウスなどを無線でつなぐ技術です。' },
  { left: 'スマートフォン', right: '決済端末', text: '読み取り部へ近づけて、非接触で支払いたい。', focus: ['タッチ', '数cm', '非接触'], choices: ['nfc', 'bluetooth', 'hdmi'], answer: 'nfc', reason: 'NFCは数cmほどまで近づけて使う近距離無線通信です。' },
  { left: 'ノートPC', right: '無線LANアクセスポイント', text: 'アクセスポイントを通して、学校のネットワークへ接続したい。', focus: ['無線LAN', 'アクセスポイント'], choices: ['wifi', 'bluetooth', 'displayport'], answer: 'wifi', reason: 'IEEE 802.11は無線LANの標準規格です。アクセスポイントから先はケーブルでネットワークへつながることもあります。' },
] as const;
