'use client';
import { useState } from 'react';
import { finalQuestions, sections, terms } from './lessonData';
import { Frame, Feedback, Stats, Celebration, Guide } from './LessonParts';

export function CommunicationCheckpoint() {
  const [index, setIndex] = useState(0), [answers, setAnswers] = useState<(number | null)[]>([null, null, null, null]);
  const question = finalQuestions[index], answer = answers[index], complete = answers.every((a, i) => a === finalQuestions[i].correct);
  return <section id="checkpoint" className="cm-section"><div className="cm-kicker"><span>✓</span><p>言葉と理由を、もう一度つなごう</p></div><h2>相手と目的から、説明しよう。</h2><div className="cm-review"><h3>重要語を確認する</h3><p>緑の数字は、このWebページの学習節です。数字から体験に戻れます。</p><div className="cm-review-terms">{terms.filter(t => t.review).map(t => <div key={t.id}><a href={`#${t.sectionId}`} aria-label={`学習${t.sectionNumber}へ戻る`}>{t.sectionNumber}</a><details><summary>{t.term}</summary><p>{t.definition}</p><p>体験では：{t.example}</p></details></div>)}</div></div><Frame id="checkpoint-lab" title="根拠を説明する、4問チェック" controls={<><button disabled={index === 0} onClick={() => setIndex(i => i - 1)}>← 前の問題</button><button disabled={index === 3} onClick={() => setIndex(i => i + 1)}>次の問題 →</button><span className="cm-counter">{index + 1} / 4</span><button onClick={() => { setAnswers([null, null, null, null]); setIndex(0); }}>4問をやり直す</button></>}><Stats answers={answers.map((v, i) => v === null ? null : v === finalQuestions[i].correct)} /><div className="cm-final-question"><h4><span>Q{index + 1}</span>{question.question}</h4><p className="cm-evidence">{question.evidence}</p><div className="cm-options cm-stacked">{question.options.map((o, i) => <button key={o} aria-pressed={answer === i} onClick={() => setAnswers(a => a.map((v, k) => k === index ? i : v))}><b>{'ABC'[i]}</b>{o}</button>)}</div><Feedback state={answer === null ? 'waiting' : answer === question.correct ? 'good' : 'bad'}>{answer === null ? <p>場面の根拠を確かめて、一つ選ぼう。選び直しもできます。</p> : <><b>{answer === question.correct ? '✓ 正解！' : '× 残念！'}</b><p>{question.why[answer]}</p><a href={`#${sections[question.section - 1].id}`}>学習{question.section}に戻って確認 →</a></>}</Feedback></div><div className="cm-completion-slot">{complete ? <Celebration text="相手・時間・情報の根拠・宛先の見え方を説明できたね。" /> : <p>正解数は最新の回答で更新します。同じ問題を選び直しても、回答数は増えません。</p>}</div></Frame><Guide mood="praise"><b>相手と目的に合わせて、手段を選ぼう。</b><p>急ぎの確認と、後から読み返す情報を組み合わせることもできるね。</p></Guide></section>;
}
