'use client';
import {useState} from 'react';
const scenes=[
 {title:'Webのリンクを開く',screen:'学校の文化祭案内',button:'文化祭ページを開く',address:'https://school.example/festival',lines:['GET /festival HTTP/1.1','Host: school.example'],meanings:['GET：指定したページをください','Host：どのサイトへの要求か'],result:'文化祭｜9月20日・体育館',connection:'school.example → DNSでIPを調べる → 198.51.100.80',explain:'URLのドメイン名とIPアドレスは別の表し方。/festival はサーバ内のページを指定する部分。HTTPSならHTTPのやり取りを暗号化して運ぶ。ここでは読みやすい形に戻した要求例を示す。'},
 {title:'メールを送る',screen:'新しいメッセージ',button:'送信する（模擬）',address:'宛先 taro@class.example ／ 件名 Festival',lines:['MAIL FROM:<hana@school.example>','RCPT TO:<taro@class.example>','DATA'],meanings:['SMTPで配送上の差出人を伝える','SMTPで配送先を伝える','このあと、メールのヘッダと本文を渡す'],result:'送信サーバがメールを受け付けました',connection:'宛先の class.example → DNSのMXで配送先サーバを調べる → そのサーバのIPへ',explain:'メールアドレスはメールボックスの宛先。通信で使うサーバのIPとは違う。ここではメールソフトからSMTPで送る例。Webメールの画面とサーバ間にはHTTPSなどが使われ、その後のメール配送にSMTPが使われる。'},
 {title:'メールの詳細を見る',screen:'受信トレイ｜Festival',button:'詳細・ヘッダーを表示（模擬）',address:'Hana から文化祭のお知らせが届きました',lines:['Received: from mail.school.example ([198.51.100.25])',' by mx.class.example; Thu, 17 Sep 2026 09:00:00 +0900','From: Hana <hana@school.example>','To: Taro <taro@class.example>','Subject: Festival'],meanings:['中継サーバが残した配送記録：この例の接続元IP','このサーバが受け取った時刻','メールに記載された差出人','メールに記載された宛先','件名（本文とは別の欄）'],result:'普段の「差出人・宛先・件名」は、この情報を読みやすく表示したもの',connection:'Receivedの198.51.100.25は中継元サーバのIPの例。差出人本人の端末のIPとは限らない。',explain:'「詳細」「ヘッダー」「メッセージのソース」などの表示機能で見られる情報の例。名称はアプリにより異なる。From/Toなどのメールのヘッダと、IP/MACのヘッダは別物。表示上のFrom/ToとSMTPの配送先が異なる場合もある。'},
 {title:'メールを受信する',screen:'メールソフト｜受信トレイ',button:'受信する（POP3の学習例）',address:'サーバに届いている1通目を取り出す',lines:['RETR 1','+OK message follows'],meanings:['メールソフト → サーバ：1通目を取り出して','サーバ → メールソフト：このあとメールの内容を返す'],result:'文化祭のお知らせが受信トレイに表示された',connection:'mail.school.example → DNSでIPを調べる → 198.51.100.25',explain:'POP3で受信する設定の例。メールアプリではIMAPなどを使う場合もある。Webメールをブラウザで開く操作が、そのままPOP3のRETRになるとは限らない。'}
];
export function FamiliarExamples(){const [scene,setScene]=useState(0),[opened,setOpened]=useState(false);const x=scenes[scene];return <details className="net-note familiar"><summary>発展：いつものクリックの裏で、何が送られる？</summary><div className="familiar-inner"><div className="familiar-tabs">{scenes.map((s,i)=><button key={s.title} aria-pressed={scene===i} onClick={()=>{setScene(i);setOpened(false)}}>{s.title}</button>)}</div><div className="familiar-grid"><section className="familiar-screen"><header>▣ {x.screen}</header><p>{x.address}</p>{scene===1&&<p className="familiar-body">文化祭は9月20日です。一緒に行こう！</p>}<button className="nx-primary" onClick={()=>setOpened(true)}>{x.button}</button><div className="familiar-result" role="status">{opened?`✓ ${x.result}`:'ボタンを押して、裏側の情報を見てみよう。'}</div></section><section className="familiar-wire"><h4>{scene===2?'メールに含まれる情報の例':'画面の裏側で使われる形式の例'}</h4>{opened?<div className="familiar-lines">{x.lines.map((line,i)=><div key={i}><code>{line}</code><span>↳ {x.meanings[i]}</span></div>)}</div>:<p className="familiar-placeholder">← 画面のボタンを押すと、ここに表示</p>}</section></div><div className="familiar-connection"><b>宛先とアドレスをつなげる</b><p>{x.connection}</p></div><p>{x.explain}</p><small>架空の名前・例示用のドメイン/IPです。主要部分のみを示し、認証・接続開始などは省略。実際にメールを送信したり、サイトへ接続したりしません。<br/>仕様：<a href="https://www.rfc-editor.org/rfc/rfc5321.html" target="_blank" rel="noreferrer">SMTP</a> ／ <a href="https://www.rfc-editor.org/rfc/rfc5322.html" target="_blank" rel="noreferrer">メールの形式</a> ／ <a href="https://www.rfc-editor.org/rfc/rfc1939.html" target="_blank" rel="noreferrer">POP3</a></small></div></details>}
