import type {ReactNode} from 'react';
function Card({icon,title,children,wide=false}:{icon:string;title:string;children:ReactNode;wide?:boolean}){return <article className={`vn-card ${wide?'vn-wide':''}`}><span className="vn-icon" aria-hidden="true">{icon}</span><div><h4>{title}</h4>{children}</div></article>}
export function VisualNotes({kind}:{kind:'network'|'layers'|'protocol'}){return <details className="net-note visual-notes"><summary>{kind==='network'?'図で補足：経路・代理通信・時刻':kind==='layers'?'図で復習：IP・MAC・包みの確認':'図で比較：TCP・UDP・4層の役割'}</summary><div className="vn-grid">{kind==='network'?<>
<Card icon="⇄" title="家の無線LANルータは、1台でいくつもの役割" wide><div className="home-router-box"><b>家庭用の無線LANルータの中身（一般的な例）</b><div className="home-roles"><div><strong>スイッチングハブ</strong><span>有線LANのポート同士をつなぐ</span><small>同じLAN内を、宛先MACで中継</small></div><div><strong>AP＝アクセスポイント</strong><span>Wi-Fiの端末をLANへつなぐ</span><small>電波と有線LANの橋渡し</small></div><div><strong>ルータ</strong><span>家庭のLANと外のネットワークをつなぐ</span><small>IPを見て次の経路を選ぶ</small></div></div></div><p>教材では役割を分けて描いています。実物では、これらが一つの箱に入っている製品が多くあります。「Wi-Fiが飛ぶ役割」と「別のネットワークへ出る役割」は別です。</p><div className="mode-compare"><section><h5>ルータモード</h5><div className="vn-flow">スマホ・PC → <b>この機器のAP／ハブ＋ルータ</b> → 回線へ</div><p>上流にルータがない構成などで、この機器が家庭のLANの出口を担当。一般にNATやIPを配るDHCPの機能も働きます。</p></section><section><h5>APモード（ブリッジモード）</h5><div className="vn-flow">スマホ・PC → <b>この機器のAP／ハブ</b> → <b>既存のルータ</b> → 回線へ</div><p>回線事業者のホームゲートウェイ等がルータを担当している場合の例。この機器のルータ機能を止め、既存LANへの有線・無線の接続を増やします。</p></section></div><p>APモードでもWi-Fiは使えます。ルータ機能を止めることと、電波を止めることは違います。対応機能・ポートの使い方・自動切替は製品により異なります。</p><a href="https://www.buffalo.jp/support/faq/detail/16000.html" target="_blank" rel="noreferrer">メーカー解説：ルータモードとAPモード</a></Card>
<Card icon="✉" title="代理の窓口＝プロキシ：何のために使う？" wide><div className="vn-flow"><b>学校・会社の端末</b> ⇄ <b>管理されたプロキシ</b> ⇄ <b>Web</b></div><p>端末の代理でWebへ依頼し、返事を端末へ返す窓口です。例えば学校や会社で、Webへのアクセスを決まった窓口にまとめて管理したいときに使います。ここでは利用者側の代理（フォワードプロキシ）を扱います。</p><div className="mode-compare"><section><h5>役立つこと</h5><ul><li><b>アクセスを管理：</b>利用者の認証や、許可したサイトへの接続制御。</li><li><b>状況を把握：</b>アクセス記録をまとめ、トラブル調査などに利用。</li><li><b>通信量を減らす場合も：</b>保存が許されたデータをキャッシュし、同じ内容を再利用。</li></ul></section><section><h5>注意すること</h5><ul><li><b>窓口に依存：</b>混雑・停止・設定ミスで、Webが遅くなったり使えなくなったりする。</li><li><b>管理の負担：</b>設定や保守が必要。サービスによってはうまく動かない。</li><li><b>記録とプライバシー：</b>管理者が扱える情報や保存範囲を決める必要がある。</li></ul></section></div><p>必ず速くなる、完全に匿名になる、という機能ではありません。HTTPSの内容を自動的に読めるわけでもなく、内容の検査には別の仕組みや端末側の設定が必要です。</p><a href="https://www.cloudflare.com/learning/cdn/glossary/reverse-proxy/" target="_blank" rel="noreferrer">フォワードプロキシの役割</a> ／ <a href="https://blog.cloudflare.com/monsters-in-the-middleboxes/" target="_blank" rel="noreferrer">HTTPSの検査とプライバシー</a></Card>
<Card icon="◷" title="NTPは時計を合わせる"><div className="vn-flow"><b>端末の時計</b> ← 時刻 ← <b>NTP</b></div><p>この例は校外の公開NTP。学校によっては校内設置もある。</p><a href="https://www.nict.go.jp/sts/ntp.html" target="_blank" rel="noreferrer">NICT公開NTP</a></Card>
<Card icon="⤴" title="残っている道へ回る"><div className="vn-flow">有線 × → 無線 ✓<br/>中継ルータ × → 別の経路 ✓</div><p>全部の道が切れると届かない。往復の道は同じとは限らない。実際の切替には時間がかかることもある。</p></Card>
</>:kind==='layers'?<>
<Card icon="◎" title="IP：最終的な通信相手"><div className="vn-flow"><b>192.0.2.10</b> → ルータ → <b>198.51.100.80</b></div><p>IPの宛先はWebサーバ。この模式例では途中のルータで宛先IPは変わらない。</p></Card>
<Card icon="↪" title="MAC：この区間の相手"><div className="vn-flow"><b>端末 → 学校ルータ</b><br/>→ 校外ルータ → サーバ</div><p>違うLANへはまずルータのMACへ。同じLAN内ならサーバのMACへ。途中にハブがあっても宛先MACはハブ自身にはしない。</p></Card>
<Card icon="✓" title="照合してから、外す"><div className="vn-stack"><b className="layer-1">MAC・FCSを確認 → 外す</b><b className="layer-2">IPを確認 → 外す</b><b className="layer-3">TCP / UDPを確認 → 外す</b><b className="layer-4">アプリが内容を読む</b></div><p>チェックサムは受信データから計算して誤りを検出。欠落したデータそのものは照合できない。TCPは順序番号や確認応答でも確かめる。</p></Card>
<Card icon="▣" title="要求は決まった形式で"><div className="vn-flow"><code>GET /festival HTTP/1.1<br/>Host: school.example</code></div><p>HTTPの要求例。「文化祭ページをください」の意味。画面は要求の主要部分を表示。POP3の <code>RETR 1</code> は「1通目のメールを取り出して」。</p><p>80＝暗号化なしのHTTPの入口、110＝暗号化なしのPOP3の入口。HTTPSは通常443、暗号化POP3は995。51000は端末側の例。</p></Card>
</>:<>
<Card icon="①②③" title="TCP：順序・確認・再送"><div className="vn-flow">① ✓　② ×　③ ✓<br/>確認応答＋SACK ↩ → ②だけ再送 → ①②③</div><p>確認応答のACK番号は「次に必要なバイト位置」。②以降を全部送り直せという意味ではない。この例はSACKで③の到着も伝え、③を保持して②だけ再送する。再送を判断する時間や確認応答の繰り返しは省略。</p></Card>
<Card icon="▶" title="UDP：届いたデータを渡す"><div className="vn-flow">① ✓　② ×　③ ✓ → アプリへ</div><p>チェックサムで誤りは検出するが、UDP自身は到達確認・再送をしない。この配信アプリは届いた部分で再生する例。</p></Card>
<Card icon="4→1" title="送信：上から下へ"><div className="vn-stack"><b className="layer-4">4 アプリケーション：要求・返事</b><b className="layer-3">3 トランスポート：データを運ぶ</b><b className="layer-2">2 インターネット：IPで経路へ</b><b className="layer-1">1 ネットワークインタフェース：信号へ</b></div></Card>
<Card icon="1→4" title="受信：下から上へ"><div className="vn-flow">信号 → MAC → IP → TCP/UDP → アプリ</div><p>①②③は実際のバイト単位の番号を簡略化。UDPの分割・補完はアプリ側の設計次第。HTTP/3はUDP上のQUICを使い、信頼性をQUICで確保する。</p></Card>
</>}<p className="vn-caption">{kind==='protocol'&&<>TCPの番号の具体例：①が1000〜1099、②が1100〜1199、③が1200〜1299なら、②未着時はACK=1100。SACK=[1200,1300)で③の受信範囲も伝える例です。<a href="https://www.rfc-editor.org/rfc/rfc2018.html" target="_blank" rel="noreferrer">SACKの仕様</a><br/></>}学習用の模式図。アドレスは例示用です。DNS・ARP・NAT・接続確立・暗号化などは省略しています。FCSとTCP/UDPチェックサムは別の範囲を検査します。チェックサムにも検出できない誤りがあり、無誤りを保証するものではありません。<br/><a href="https://www.rfc-editor.org/rfc/rfc9293" target="_blank" rel="noreferrer">TCP仕様</a> ／ <a href="https://www.rfc-editor.org/rfc/rfc768" target="_blank" rel="noreferrer">UDP仕様</a> ／ <a href="https://www.rfc-editor.org/rfc/rfc9110.html" target="_blank" rel="noreferrer">HTTP仕様</a> ／ <a href="https://www.rfc-editor.org/rfc/rfc1939.html" target="_blank" rel="noreferrer">POP3仕様</a></p></div></details>}
