'use client';
import {useState} from 'react';
import {Guide} from './LessonParts';
import {sections,terms} from './model';

const questions=[
 {q:'URLを入力してから、Webページが表示されるまでの順は？',evidence:'最初、PCはwww.example.comのIPアドレスを知りません。',options:['DNSでIPを調べる → Webサーバへ要求 → 応答を受けて表示','DNSからページの本文を受け取る → ルータが画像を作る','Webサーバに要求 → DNSでIPを調べる → 表示'],correct:0,section:1,why:['✓ 正解！ DNSは宛先IPを調べ、ページ本体はWebサーバが返します。','× DNSはページの本文を返しません。ルータも画像を作りません。','× 宛先が分からない場合、Webサーバへの要求より先に名前を調べます。']},
 {q:'受信側メールサーバに届いたメールを、複数の端末から同じ状態で読みたい。どの役割が合う？',evidence:'SMTPでサーバ間の配送は終わっています。今は受信者が読む段階です。',options:['SMTPで毎回送信し直す','IMAPでサーバ上のメールを閲覧する','ルータの経路表に本文を保存する'],correct:1,section:2,why:['× SMTPは送信・転送の役です。受信者が読む方法を選びます。','✓ 正解！ IMAPはサーバ上のメールを管理し、複数端末から同じ状態を見やすくします。','× 経路表には次の転送先を記録します。メール本文は保存しません。']},
 {q:'偶数パリティで、送信中に2ビットが反転した。受信側はどう判断する？',evidence:'送信時も受信時も、8ビット中の「1」の個数は偶数になっています。',options:['必ず誤りを検出し、元の値へ直せる','誤りを検出できない場合がある','ファイアウォールが自動で2ビットを元に戻す'],correct:1,section:6,why:['× 2ビット反転では偶数のままになる場合があり、パリティだけで訂正もできません。','✓ 正解！ 偶数個の反転は偶数の約束を保つことがあり、見逃します。','× ファイアウォールは通信を許可・拒否する機能で、ビットの訂正はしません。']},
] as const;
export default function Checkpoint(){
 const [answers,setAnswers]=useState<(number|null)[]>([null,null,null]);
 const answered=answers.filter(x=>x!==null).length,correct=answers.filter((x,i)=>x===questions[i].correct).length;
 return <section id="checkpoint" className="in-section"><div className="in-kicker"><span>✓</span><p>用語としくみをつなげよう</p></div><h2>学んだことを確かめよう。</h2><div className="in-panel"><h3>プリント09の重要語</h3><p className="in-small">緑の数字は、このWebページの学習節1〜6です。プリントの丸数字の空欄番号とは違います。数字から体験に戻れます。</p><div className="in-review-terms">{terms.map(([blank,term,detail,section])=><div key={blank}><a href={`#${sections[section-1][0]}`} aria-label={`学習${section}へ戻る`}>{section}</a><details><summary>{blank} {term}</summary><p>{detail}</p></details></div>)}</div></div><div className="in-quiz"><div className="in-heading"><h3>しくみを説明する、3問チェック</h3><button type="button" onClick={()=>setAnswers([null,null,null])}>3問をやり直す</button></div><div className="in-stats" role="status">{[['回答済み',`${answered}/3`],['正解',`${correct}/3`],['残り',`${3-answered}`],['正答率',answered?`${Math.round(correct/answered*100)}%`:'—']].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div><p className="in-small">選び直せます。回答数は各問題を一度ずつ数え、正解数は最新の選択で更新します。</p>{questions.map((question,i)=><fieldset key={question.q} className="in-question"><legend><span>Q{i+1}</span>{question.q}</legend><p className="in-evidence">{question.evidence}</p><div className="in-quiz-options">{question.options.map((option,j)=><button type="button" key={option} aria-pressed={answers[i]===j} onClick={()=>setAnswers(old=>old.map((value,k)=>k===i?j:value))}><span>{'ABC'[j]}</span>{option}</button>)}</div><div className={`in-quiz-feedback ${answers[i]===question.correct?'is-correct':''}`} role="status">{answers[i]===null?'図や本文を思い出して、1つ選ぼう。':question.why[answers[i]!]}</div><a className="in-text-link" href={`#${sections[question.section-1][0]}`}>学習{question.section}へ戻って確かめる →</a></fieldset>)}<div className={correct===3?'in-finale complete':'in-finale'}><Guide mood={correct===3?'celebrating':'praise'}><b>{correct===3?'3問とも正解！ 届くしくみと守り方がつながったね。':'最後に、流れを自分の言葉で説明してみよう。'}</b><p>WebはDNSから宛先を知り、メールはSMTPで受信側サーバへ届きます。情報を守る規則と、パリティで検出できる誤りの範囲も説明できるかな？</p></Guide></div></div></section>;
}
