'use client';
import {useState} from 'react';
import {Guide} from './Parts';
import {terms,sections} from './model';

const questions=[
 {q:'NAPTルータに、宛先203.0.113.1:60000の返事が到着。どちらへ戻す？',evidence:'変換表：A → 203.0.113.1:50000 ／ B → 203.0.113.1:60000',options:['端末A','端末B','AとBの両方'],correct:1,section:2,why:['Aの対応は50000です。返信の宛先ポート60000に一致する行を探そう。','○ 正解。60000の行からBの内側IP・ポートへ変換します。','同じグローバルIPでも、ポートと対応表で返信先を区別します。']},
 {q:'192.168.1.100/26のネットワークアドレスと、使える台数の組は？',evidence:'/26 は左から26ビットがネットワーク部。第4組では、左の2ビットがネットワーク部です。',options:['192.168.1.0 ／ 254台','192.168.1.64 ／ 64台','192.168.1.64 ／ 62台'],correct:2,section:3,why:['それは/24の場合です。/26では第4組の左2ビットもネットワーク部になります。','範囲は合っています。64通りの両端を除くと、使える候補は62個です。','○ 正解。100は64〜127に入り、端末やルータに使える候補は2⁶−2 = 62個です。']},
 {q:'初めて訪れるWebページ。名前を調べて表示する順番は？',evidence:'端末はWebサーバのIPを知らず、DNSにキャッシュがないものとします。',options:['DNSに依頼 → 必要なDNSをたどる → IPを受け取る → Webサーバと通信','ルートDNSからWebページ本体を受け取る','NAPTに名前を渡す → NAPTがページを作る'],correct:0,section:5,why:['○ 正解。名前解決のあとにWebサーバと通信します。','DNSはページ本体を返しません。','NAPTはIP・ポートを変換する仕組みです。']},
];
export default function Checkpoint(){const [answers,setAnswers]=useState<(number|null)[]>([null,null,null]);const answered=answers.filter(a=>a!==null).length,correct=answers.filter((a,i)=>a===questions[i].correct).length;return <section id="checkpoint" className="in-section"><div className="in-kicker"><span>✓</span><p>学んだ言葉を、もう一度つなごう</p></div><h2>言葉としくみを説明しよう。</h2><div className="in-panel"><h3>重要語を確認する</h3><p className="in-small">気になる言葉を開いて意味を確かめよう。左の緑の数字から、体験した節に戻れます。</p><div className="in-review-terms">{terms.map(([blank,term,detail,section])=><div key={blank}><a href={`#${sections[section-1][0]}`} aria-label={`学習${section}へ戻る`}>{section}</a><details><summary>{term}</summary><p>{detail}</p></details></div>)}</div><p className="in-small">接続台数の計算は学習3の入力図でもう一度確認できます。</p></div><div className="in-quiz"><div className="in-heading"><h3>しくみを説明する、3問チェック</h3><button onClick={()=>setAnswers([null,null,null])}>3問をやり直す</button></div><div className="in-stats" role="status">{[['回答済み',`${answered}/3`],['正解',`${correct}/3`],['残り',3-answered],['正答率',answered?`${Math.round(correct/answered*100)}%`:'—']].map(([label,value])=><div key={label}><small>{label}</small><b>{value}</b></div>)}</div><p className="in-small">選び直せます。正解数は最新の回答で更新します。</p>{questions.map((q,i)=><fieldset key={q.q} className="in-question"><legend><span>Q{i+1}</span>{q.q}</legend><p className="in-evidence">{q.evidence}</p><div className="in-quiz-options">{q.options.map((opt,j)=><button key={opt} aria-pressed={answers[i]===j} onClick={()=>setAnswers(a=>a.map((x,k)=>k===i?j:x))}><span>{'ABC'[j]}</span>{opt}</button>)}</div><div className={`in-quiz-feedback ${answers[i]===q.correct?'is-correct':''}`} role="status">{answers[i]===null?'根拠を見て、1つ選ぼう。':q.why[answers[i]!]}</div>{i===1&&answers[i]!==null&&<div className="in-prefix-explanation"><b>なぜ /26 で4つの範囲に分かれる？</b><p>32ビットのうち左から26ビットがネットワーク部。先頭の24ビットは「192.168.1」で、第4組の<strong>左2ビット</strong>もネットワーク部です。その2ビットは <code>00</code>・<code>01</code>・<code>10</code>・<code>11</code> の4通り。残り6ビットは自由に変わります。</p><div className="in-prefix-groups"><span><code>00</code> → 0〜63</span><span><code>01</code> → 64〜127</span><span><code>10</code> → 128〜191</span><span><code>11</code> → 192〜255</span></div><p>100を2進数にすると <code>01100100</code>。先頭2ビットは <code>01</code> なので、<strong>64〜127</strong> の組です。両端の <code>192.168.1.64</code> はネットワークアドレス、<code>192.168.1.127</code> はブロードキャストアドレス。残る <strong>65〜126の62個</strong> が端末やルータに使える住所の候補です。</p></div>}<a className="in-text-link" href={`#${sections[q.section-1][0]}`}>学習{q.section}に戻って確かめる →</a></fieldset>)}<div className={correct===3?'in-finale complete':'in-finale'}><Guide mood={correct===3?'celebrating':'praise'}><b>{correct===3?'3問とも正解！ つながる理由が見えてきたね。':'最後は、自分の言葉でつないでみよう。'}</b><p>DHCPで設定を受け取り、DNSで名前解決をする。宛先がLANの外ならデフォルトゲートウェイへ。NAPTで変換した通信の返事が、対応表を使って自分の端末に届く理由まで説明できるかな？</p></Guide></div></div></section>}
